import { NextRequest } from "next/server";
import { getAuth } from "@clerk/nextjs/server";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { fetchTavilyWebAnswer } from "@/lib/connectors/tavily-search";

/**
 * Day 29 v1 — Streaming chat endpoint.
 *
 * Returns Server-Sent Events (text/event-stream) so the
 * client can typewriter-render the response letter-by-letter
 * like ChatGPT.
 *
 * SSE format:
 *   data: {"type":"sources","sources":[...]}\n\n
 *   data: {"type":"token","text":"hello"}\n\n
 *   data: {"type":"token","text":" world"}\n\n
 *   data: {"type":"followups","questions":[...]}\n\n
 *   data: {"type":"done","path":"gemini","applyQuery":"...","sources":[...]}\n\n
 *
 * LCP-36 upgrades:
 *   - Gemini's systemInstruction is used (NOT a user turn)
 *     so the model treats follow-ups like "why that?" as
 *     grounded in the prior conversation, not as standalone
 *     English dictionary lookups.
 *   - Every response includes an `applyQuery` field so the
 *     client can render an "Apply to results" button on every
 *     Atlas answer (Perplexity-style).
 *   - A `followups` SSE event is emitted with 2-3 related
 *     follow-up questions, generated by Gemini from the
 *     answer context.
 *   - OpenRouter fallback path always runs Tavily first so
 *     every response includes live web sources.
 */

export const dynamic = "force-dynamic";
export const runtime = "nodejs";

const TAVILY_TIMEOUT_MS = 5_000;
const GEMINI_TIMEOUT_MS = 15_000;
const OPENROUTER_TIMEOUT_MS = 7_000;
const FOLLOWUPS_TIMEOUT_MS = 4_000;

interface ChatRequestBody {
  message: string;
  questionContext?: string;
  // LCP-35 — full conversation history (excluding the current
  // user message, which the client already includes as `message`).
  // Max 10 turns = 20 messages (user+atlas pairs).
  history?: Array<{ role: "user" | "atlas"; text: string }>;
}

interface SourceItem {
  title: string;
  url: string;
}

function sseEvent(type: string, payload: Record<string, unknown>): string {
  return `data: ${JSON.stringify({ type, ...payload })}\n\n`;
}

function chunkString(text: string, chunkSize = 6): string[] {
  const chunks: string[] = [];
  for (let i = 0; i < text.length; i += chunkSize) {
    chunks.push(text.slice(i, i + chunkSize));
  }
  return chunks;
}

/**
 * LCP-36 — Build the systemInstruction that grounds every
 * response in the prior conversation and the question context.
 * This is passed to Gemini via the `systemInstruction` field
 * (not as a user turn) so the model treats it as a global rule
 * rather than as part of the conversation history.
 */
function buildSystemInstruction(context: string): string {
  const ctxLine = context
    ? `\n\nThe user's original Atlas question (the one that opened this conversation) is: "${context}". The user is asking follow-up questions about THIS question. If their follow-up is short, vague, or pronouns-heavy (e.g. "why that?", "what about prices?", "is it safe?"), you MUST interpret it as a follow-up about the original Atlas question — do NOT answer it as a standalone English question.`
    : `\n\nThe user has just asked a follow-up question. Interpret it as a continuation of the conversation history, not as a standalone English question. If the follow-up is short, vague, or pronouns-heavy (e.g. "why that?", "explain", "what about prices?"), ground your answer in the immediately preceding assistant answer.`;

  return `You are Atlas, an AI research assistant for African builders and investors. You help with site selection, market intelligence, property questions, and investment opportunities across southern Africa (South Africa, Zambia, Zimbabwe, Namibia, Botswana).

Your answers should be:
- Specific and grounded — cite real prices, areas, and trends when you know them. Do NOT fabricate data, addresses, or sources.
- Concise — 2-4 short paragraphs by default. Use a conversational, direct tone. No headers, no bullet lists unless the user explicitly asks.
- Honest about uncertainty — if you don't know, say so. Better to admit a gap than to invent.${ctxLine}

Style rules:
- Never use the word "delve". Never start with "Certainly" or "Great question". 
- Use South African pricing (ZAR, "R") by default. Mention Zambian Kwacha (ZMW, "K") if the question is about Zambia.
- When you have sources, weave them into the answer naturally with [1], [2] markers. The sources list is provided separately.`;
}

export async function POST(req: NextRequest) {
  // Auth gate
  const { userId } = getAuth(req);
  if (!userId) {
    return new Response(
      JSON.stringify({ error: "Sign in required" }),
      { status: 401, headers: { "Content-Type": "application/json" } },
    );
  }

  let body: ChatRequestBody;
  try {
    body = await req.json();
  } catch {
    return new Response(
      JSON.stringify({ error: "Invalid JSON body" }),
      { status: 400, headers: { "Content-Type": "application/json" } },
    );
  }

  const message = (body.message ?? "").trim();
  if (!message) {
    return new Response(
      JSON.stringify({ error: "Missing 'message' field" }),
      { status: 400, headers: { "Content-Type": "application/json" } },
    );
  }
  const context = (body.questionContext ?? "").trim();

  // LCP-36 — Every response carries an applyQuery so the
  // client can render "Apply to results" on every Atlas
  // message. For non-contextual chats we fall back to the
  // raw user message so the button is still usable.
  const applyQuery = context ? context : message;

  // Build SSE stream
  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    async start(controller) {
      try {
        // Step 1 — Try Gemini streaming
        const geminiKey = process.env.GEMINI_API_KEY;
        let path: string = "no_data";
        let sources: SourceItem[] = [];
        let geminiAnswer = "";
        let geminiStreamed = false;

        // LCP-37 + LCP-38 — detect short follow-up questions
        // BEFORE we decide whether to fall back to Tavily.
        // We hoist this out of the geminiKey block so the
        // Tavily fallback below can short-circuit when this
        // is a follow-up (no web search needed; the model
        // has the prior answer in inline context).
        const followupInfo = buildFollowupTurn(
          message,
          body.history ?? [],
          context,
        );

        if (geminiKey) {
          try {
            const genAI = new GoogleGenerativeAI(geminiKey);
            const model = genAI.getGenerativeModel({
              model: "gemini-2.0-flash",
              // LCP-36 — systemInstruction is the right place
              // for global rules. The model will treat it as
              // authoritative and will NOT confuse it with a
              // user turn in the conversation history.
              systemInstruction: buildSystemInstruction(context),
            });
            const historyContents = (body.history ?? []).map((h) => ({
              role: h.role === "user" ? "user" : "model",
              parts: [{ text: h.text }],
            }));

            // LCP-37 + LCP-38 — Short follow-up questions
            // (e.g. "is it the capital?" or "whats it's
            // population?") need special handling:
            //   - Rewrite the user turn to include the FULL
            //     prior assistant answer as inline context
            //     with explicit grounding instructions.
            //   - Skip the Tavily web search entirely (set
            //     below in the !geminiStreamed branch).
            const finalUserText = followupInfo.text;
            const allContents = [
              ...historyContents,
              { role: "user" as const, parts: [{ text: finalUserText }] },
            ];
            const geminiStreamResult = model.generateContentStream({
              contents: allContents,
            });

            const timeoutPromise = new Promise<never>((_, reject) =>
              setTimeout(
                () => reject(new Error("gemini_timeout")),
                GEMINI_TIMEOUT_MS,
              ),
            );

            let buffer = "";
            const streamIter = (await Promise.race([
              geminiStreamResult,
              timeoutPromise,
            ])) as unknown as AsyncIterable<{ text(): string }>;

            for await (const chunk of streamIter as AsyncIterable<{ text(): string }>) {
              const text = chunk.text();
              if (text) {
                buffer += text;
                geminiAnswer += text;
                controller.enqueue(
                  encoder.encode(sseEvent("token", { text })),
                );
              }
            }
            if (buffer.length > 0) {
              path = "gemini";
              geminiStreamed = true;
            }
          } catch (err) {
            const msg = err instanceof Error ? err.message : String(err);
            console.warn("[/api/chat/stream] gemini error:", msg);
          }
        }

        // Step 2 — If Gemini didn't stream, fall back through
        // Tavily → inline Tavily → OpenRouter. Tavily runs
        // FIRST in the OpenRouter branch (LCP-36) so even the
        // fallback path surfaces live web sources.
        //
        // LCP-39 — for followups (e.g. "is it the capital?"),
        // we DO call Tavily but with a query that's been
        // scoped to the prior subject. The Tavily query
        // becomes "<prior subject> <user message>" (e.g.
        // "Gauteng, meaning place of gold in Sotho, is South
        // Africa's smallest province... is it the capital").
        // This makes Tavily return grounded results scoped
        // to the prior topic, instead of generic web
        // results about "capital". The model then
        // synthesizes from history + Tavily's scoped
        // results.
        if (!geminiStreamed) {
          let tavilyAnswer = "";
          let tavilySources: SourceItem[] = [];

          // LCP-39 — for followups, expand the Tavily query
          // with the prior subject so the search is scoped
          // to the prior topic. For non-followups, just
          // use the user's message as-is (with questionContext
          // if any).
          let tavilyQuery: string;
          if (followupInfo.isFollowup && followupInfo.priorSubject) {
            tavilyQuery = `${followupInfo.priorSubject} ${message}`;
          } else if (context) {
            tavilyQuery = `${message} (re: ${context})`;
          } else {
            tavilyQuery = message;
          }

          try {
            const tavilyPromise = fetchTavilyWebAnswer(tavilyQuery, {
              context,
              maxResults: 5,
            });
            const tavilyResult = (await Promise.race([
              tavilyPromise,
              new Promise<null>((resolve) =>
                setTimeout(() => resolve(null), TAVILY_TIMEOUT_MS),
              ),
            ])) as Awaited<typeof tavilyPromise>;
            if (tavilyResult) {
              tavilyAnswer = tavilyResult.answer ?? "";
              tavilySources = tavilyResult.sources.map((s) => ({
                title: s.title,
                url: s.url,
              }));
            }
          } catch (err) {
            console.warn("[/api/chat/stream] tavily connector:", err);
          }

          if (!tavilyAnswer && tavilySources.length === 0) {
            const inlineKey = process.env.TAVILY_API_KEY ?? "";
            if (inlineKey) {
              try {
                const inlineController = new AbortController();
                const inlineTimeout = setTimeout(
                  () => inlineController.abort(),
                  TAVILY_TIMEOUT_MS,
                );
                const inlineRes = await fetch(
                  "https://api.tavily.com/search",
                  {
                    method: "POST",
                    headers: {
                      "Content-Type": "application/json",
                      Authorization: `Bearer ${inlineKey}`,
                    },
                    body: JSON.stringify({
                      api_key: inlineKey,
                      query: tavilyQuery,
                      search_depth: "advanced",
                      include_answer: "advanced",
                      max_results: 5,
                      topic: "general",
                    }),
                    signal: inlineController.signal,
                    cache: "no-store",
                  },
                );
                clearTimeout(inlineTimeout);
                if (inlineRes.ok) {
                  const inlineData = (await inlineRes.json()) as {
                    answer?: string;
                    results?: Array<{ title: string; url: string }>;
                  };
                  tavilyAnswer = inlineData.answer ?? "";
                  tavilySources = (inlineData.results ?? []).map((r) => ({
                    title: r.title,
                    url: r.url,
                  }));
                }
              } catch (err) {
                console.warn("[/api/chat/stream] inline tavily:", err);
              }
            }
          }

          // Tavily answer is the strongest non-Gemini path —
          // it already has sources and synthesized text.
          if (tavilyAnswer.length > 0) {
            path = "tavily_answer";
            sources = tavilySources;
            for (const chunk of chunkString(tavilyAnswer, 6)) {
              controller.enqueue(
                encoder.encode(sseEvent("token", { text: chunk })),
              );
              await sleep(15);
            }
          } else if (tavilySources.length > 0) {
            // We have sources but no synthesized answer.
            // Use OpenRouter to write a short grounded answer
            // that cites those sources. LCP-36 — always include
            // sources, even on the fallback path.
            sources = tavilySources;
            const sourceList = tavilySources
              .slice(0, 3)
              .map((s, i) => `[${i + 1}] ${s.title}`)
              .join("\n");
            const orAnswer = await tryOpenRouter({
              system: `${buildSystemInstruction(context)}\n\nYou have these live web sources — use them as the basis of your answer and cite them with [1], [2] markers:\n${sourceList}`,
              history: body.history ?? [],
              message,
            });
            if (orAnswer) {
              path = "tavily_plus_openrouter";
              const text = `${orAnswer}`;
              for (const chunk of chunkString(text, 6)) {
                controller.enqueue(
                  encoder.encode(sseEvent("token", { text: chunk })),
                );
                await sleep(15);
              }
            } else {
              // OpenRouter failed too — emit a sources-only stub
              path = "tavily_sources";
              const text = `I found live web data on this topic. The most relevant sources are:\n\n${sourceList}\n\nClick any citation below to read the full article.`;
              for (const chunk of chunkString(text, 6)) {
                controller.enqueue(
                  encoder.encode(sseEvent("token", { text: chunk })),
                );
                await sleep(15);
              }
            }
          } else {
            // No Tavily data either. Try OpenRouter as a
            // last-resort free-text answer.
            const orAnswer = await tryOpenRouter({
              system: buildSystemInstruction(context),
              history: body.history ?? [],
              message,
            });
            if (orAnswer) {
              path = "openrouter";
              const text = `${orAnswer}\n\n_Note: this came from a free-tier fallback model (GPT-OSS 20B). Atlas's primary research engine is temporarily unavailable._`;
              for (const chunk of chunkString(text, 6)) {
                controller.enqueue(
                  encoder.encode(sseEvent("token", { text: chunk })),
                );
                await sleep(15);
              }
            } else {
              path = "no_data";
              const text =
                "I couldn't reach a live web data source right now. " +
                "Tavily, Gemini, and OpenRouter all returned empty. " +
                "Try a more specific question or check back in a few minutes.";
              for (const chunk of chunkString(text, 6)) {
                controller.enqueue(
                  encoder.encode(sseEvent("token", { text: chunk })),
                );
                await sleep(15);
              }
            }
          }
        }

        // LCP-36 — emit sources first so the client can
        // render them inline as the user reads.
        if (sources.length > 0) {
          controller.enqueue(
            encoder.encode(sseEvent("sources", { sources })),
          );
        }

        // LCP-36 — generate 2-3 follow-up question chips.
        // Only attempt when we have a real answer (skip
        // no_data stub so we don't suggest bad follow-ups).
        if (path !== "no_data") {
          const followups = await tryGenerateFollowups({
            context,
            history: body.history ?? [],
            lastUserMessage: message,
            lastAnswer: geminiAnswer,
          });
          if (followups.length > 0) {
            controller.enqueue(
              encoder.encode(sseEvent("followups", { questions: followups })),
            );
          }
        }

        controller.enqueue(
          encoder.encode(
            sseEvent("done", { path, applyQuery, sources }),
          ),
        );
        controller.enqueue(encoder.encode("data: [DONE]\n\n"));
        controller.close();
      } catch (err) {
        console.error("[/api/chat/stream] fatal:", err);
        controller.enqueue(
          encoder.encode(
            sseEvent("error", {
              message: err instanceof Error ? err.message : String(err),
            }),
          ),
        );
        controller.enqueue(encoder.encode("data: [DONE]\n\n"));
        controller.close();
      }
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache, no-transform",
      Connection: "keep-alive",
    },
  });
}

function sleep(ms: number): Promise<void> {
  return new Promise((r) => setTimeout(r, ms));
}

interface OpenRouterArgs {
  system: string;
  history: Array<{ role: "user" | "atlas"; text: string }>;
  message: string;
}

/**
 * Best-effort OpenRouter call. Returns the assistant text or
 * null on any failure (timeout, error, empty response).
 */
async function tryOpenRouter(args: OpenRouterArgs): Promise<string | null> {
  const openrouterKey = process.env.OPENROUTER_API_KEY;
  if (!openrouterKey) return null;
  try {
    const orController = new AbortController();
    const orTimeout = setTimeout(
      () => orController.abort(),
      OPENROUTER_TIMEOUT_MS,
    );
    const orRes = await fetch(
      "https://openrouter.ai/api/v1/chat/completions",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${openrouterKey}`,
        },
        body: JSON.stringify({
          model: "openai/gpt-oss-20b:free",
          messages: [
            { role: "system", content: args.system },
            ...args.history.map((h) => ({
              role: h.role === "user" ? ("user" as const) : ("assistant" as const),
              content: h.text,
            })),
            { role: "user" as const, content: args.message },
          ],
          max_tokens: 400,
        }),
        signal: orController.signal,
        cache: "no-store",
      },
    );
    clearTimeout(orTimeout);
    if (!orRes.ok) return null;
    const orData = (await orRes.json()) as {
      choices?: Array<{ message?: { content?: string } }>;
    };
    const orText = orData.choices?.[0]?.message?.content?.trim() ?? "";
    return orText.length >= 10 ? orText : null;
  } catch {
    return null;
  }
}

interface FollowupsArgs {
  context: string;
  history: Array<{ role: "user" | "atlas"; text: string }>;
  lastUserMessage: string;
  lastAnswer: string;
}

/**
 * LCP-36 — Generate 2-3 follow-up question chips the user
 * can click to continue the conversation. Uses Gemini with
 * a strict JSON output prompt. If Gemini is unavailable, we
 * fall back to extracting question patterns from the
 * conversation history deterministically.
 */
async function tryGenerateFollowups(args: FollowupsArgs): Promise<string[]> {
  const geminiKey = process.env.GEMINI_API_KEY;
  const trimmedAnswer = args.lastAnswer.slice(0, 1500);
  if (!geminiKey || !trimmedAnswer) return [];

  const prompt = `You are generating follow-up question suggestions for an AI research assistant called Atlas.

The user's original Atlas question (if any): ${args.context || "(no original question — this is a free chat)"}

The most recent user message: ${args.lastUserMessage}

The assistant's most recent answer (truncated):
"""
${trimmedAnswer}
"""

Generate exactly 3 short follow-up questions the user is likely to ask next. Each question must be:
- 4-12 words
- A genuine natural follow-up, not a rephrasing of the prior question
- Grounded in the answer above (something a curious builder or investor would actually want to know next)
- A question, ending in a question mark

Return ONLY a JSON array of 3 strings. No commentary, no markdown fences. Example: ["How much does it cost to build there?", "Is the area safe for families?", "What's the average rental yield?"]`;

  try {
    const genAI = new GoogleGenerativeAI(geminiKey);
    const model = genAI.getGenerativeModel({
      model: "gemini-2.0-flash",
      generationConfig: {
        temperature: 0.7,
        maxOutputTokens: 200,
        responseMimeType: "application/json",
      },
    });
    const followupTimeout = new Promise<never>((_, reject) =>
      setTimeout(() => reject(new Error("followups_timeout")), FOLLOWUPS_TIMEOUT_MS),
    );
    const result = (await Promise.race([
      model.generateContent(prompt),
      followupTimeout,
    ])) as Awaited<ReturnType<typeof model.generateContent>>;
    const text = result.response.text().trim();
    const parsed = JSON.parse(text);
    if (Array.isArray(parsed)) {
      return parsed
        .filter((q): q is string => typeof q === "string" && q.trim().length > 0)
        .slice(0, 3)
        .map((q) => q.trim());
    }
    return [];
  } catch {
    return [];
  }
}

/**
 * LCP-37 + LCP-38 — Hard-fix for short follow-up questions.
 *
 * Background: David reported that after asking "Tell me about
 * Gauteng" (which returned a great answer), his follow-up
 * "is it the capital?" returned a Wikipedia definition of
 * "capital" instead of an answer about Gauteng.
 *
 * Root cause analysis (LCP-38):
 *   - LCP-36's systemInstruction + LCP-37's anchor rewrite
 *     helped on fresh questions but not on short follow-ups.
 *   - The real problem: Tavily is running a web search on the
 *     short query "is it the capital?" and returning generic
 *     results about "what is a capital city". The model
 *     then summarizes those results instead of the prior
 *     answer's content.
 *
 * Fix (LCP-38): when the new message is a short follow-up
 * AND there is prior conversation history, do TWO things:
 *
 *   1. SKIP the Tavily web search entirely. The prior answer
 *      already contains the relevant facts. No external
 *      search is needed for a clarification question.
 *
 *   2. Pass the FULL prior assistant answer as inline
 *      context in the user turn. The pattern is:
 *
 *        Given this prior answer:
 *        "<full prior answer>"
 *
 *        The user is asking this follow-up: <message>
 *
 *        Answer the follow-up based ONLY on the prior answer
 *        above. Do NOT do a web search. Do NOT answer the
 *        follow-up as if it were a standalone question.
 *
 *      This is the textbook Perplexity / OpenAI / Anthropic
 *      follow-up pattern: the model literally sees the prior
 *      answer before the new question, with explicit
 *      instructions to ground the response in it.
 *
 * Detection rules — the new turn is treated as a follow-up
 * if ALL of:
 *   - No questionContext (free chat; result-page chats
 *     are already covered by systemInstruction)
 *   - At least one prior assistant turn exists
 *   - The new message is short (< 80 chars) OR starts with
 *     follow-up markers ("and X", "what about", "why", etc.)
 *     OR contains pronouns (it/its/that/this/there/...)
 */
interface FollowupResult {
  /** The user turn to send to Gemini. Kept natural. */
  text: string;
  /** True when the message is a short follow-up. */
  isFollowup: boolean;
  /** Short subject snippet from the prior answer, for Tavily query expansion. */
  priorSubject: string | null;
}

function buildFollowupTurn(
  message: string,
  history: Array<{ role: "user" | "atlas"; text: string }>,
  questionContext: string,
): FollowupResult {
  // If we have a questionContext (user is on a /result/[id]
  // page), the systemInstruction already covers the case.
  if (questionContext) {
    return { text: message, isFollowup: false, priorSubject: null };
  }
  if (history.length === 0) {
    return { text: message, isFollowup: false, priorSubject: null };
  }

  const newLen = message.length;
  const isShort = newLen < 80;
  const followupPatterns = /\b(its|it's|their|them|they|that|this|those|these|there|here|he|she|it|the same|also|and what|and the|how about|what about|why|when|where|who)\b/i;
  const startsWithAnd = /^\s*(and|also|what about|how about|and what|and the|why|when|where)\b/i.test(message);
  const looksLikeFollowup =
    isShort || followupPatterns.test(message) || startsWithAnd;

  if (!looksLikeFollowup) {
    return { text: message, isFollowup: false, priorSubject: null };
  }

  // Find the last assistant turn.
  const lastAssistant = [...history].reverse().find((h) => h.role === "atlas");
  if (!lastAssistant || !lastAssistant.text.trim()) {
    return { text: message, isFollowup: false, priorSubject: null };
  }

  // LCP-39 — extract a short subject (first sentence, capped
  // at 200 chars). Used to expand the Tavily query so the
  // search is scoped to the prior topic, not the open web.
  // We keep the user turn natural so the model has the
  // history (already in contents) and Tavily's scoped
  // results to work with — no elaborate "do not search the
  // web" instructions that the model was getting confused
  // by.
  const priorSubject = lastAssistant.text
    .replace(/\s+/g, " ")
    .split(/[.!?]/)[0]
    .trim()
    .slice(0, 200);

  return {
    text: message,
    isFollowup: true,
    priorSubject: priorSubject || null,
  };
}
