"use client";

import { useState } from "react";

interface ExportData {
  question: string;
  vertical: string;
  city?: string;
  country?: string;
  model?: string;
  echo?: string;
  rankedSites: any[];
  plan?: any;
  answer?: string;
  sources?: any[];
}

function downloadFile(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function toCSV(sites: any[]): string {
  const header = "rank,name,suburb,score,confidence,lat,lng,rationale";
  const rows = sites.map((s) =>
    [
      s.rank,
      JSON.stringify(s.name ?? ""),
      JSON.stringify(s.suburb ?? ""),
      s.score ?? 0,
      s.confidence ?? 0,
      s.lat ?? 0,
      s.lng ?? 0,
      JSON.stringify((s.rationale ?? "").replace(/"/g, '""')),
    ].join(",")
  );
  return [header, ...rows].join("\n");
}

function toMarkdown(d: ExportData): string {
  const lines: string[] = [];
  lines.push(`# Atlas — ${d.vertical.replace(/_/g, " ")}`);
  lines.push("");
  if ((d as any).resultUrl) {
    lines.push(`**View online:** ${(d as any).resultUrl}`);
    lines.push("");
  }
  lines.push(`**Question:** ${d.question}`);
  if (d.city) lines.push(`**City:** ${d.city}${d.country ? `, ${d.country}` : ""}`);
  lines.push(`**Model:** ${d.model ?? "Atlas Stub"}`);
  if (d.echo) lines.push(`**Status:** ${d.echo}`);
  lines.push("");
  if (d.answer) {
    lines.push("## Research Answer");
    lines.push(d.answer);
    lines.push("");
  }
  lines.push(`## Top ${d.rankedSites.length} Sites`);
  lines.push("");
  for (const s of d.rankedSites) {
    lines.push(`### ${s.rank}. ${s.name}${s.suburb ? ` — ${s.suburb}` : ""}`);
    lines.push(`**Score:** ${(s.score * 100).toFixed(0)}% · **Confidence:** ${(s.confidence * 100).toFixed(0)}%`);
    lines.push(`**Location:** ${s.lat?.toFixed(4)}, ${s.lng?.toFixed(4)}`);
    if (s.rationale) lines.push(`**Why:** ${s.rationale}`);
    if (s.advantages) {
      lines.push("**Advantages:**");
      const advs = s.advantages;
      if (advs.economic) lines.push(`- Economic: ${advs.economic}`);
      if (advs.geographic) lines.push(`- Geographic: ${advs.geographic}`);
      if (advs.logistical) lines.push(`- Logistical: ${advs.logistical}`);
      if (advs.demographic) lines.push(`- Demographic: ${advs.demographic}`);
    }
    if (s.disadvantages) lines.push(`**Drawbacks:** ${s.disadvantages}`);
    if (s.competition && Array.isArray(s.competition) && s.competition.length > 0) {
      lines.push(`**Nearby competitors:** ${s.competition.slice(0, 5).join(", ")}`);
    }
    if (s.signals && Array.isArray(s.signals) && s.signals.length > 0) {
      lines.push(`**Signals (${s.signals.length}):**`);
      for (const sig of s.signals.slice(0, 8)) {
        lines.push(`- [${sig.source}] ${sig.label ?? sig.type}`);
      }
    }
    lines.push("");
  }
  if (d.sources && d.sources.length > 0) {
    lines.push("## Sources");
    for (const s of d.sources) {
      lines.push(`- [${s.title ?? s.url}](${s.url})`);
    }
    lines.push("");
  }
  lines.push("---");
  lines.push(`Generated by Atlas · ${new Date().toISOString()}`);
  return lines.join("\n");
}

export function ResultExportButton({ data, resultId }: { data: ExportData; resultId?: string }) {
  const [open, setOpen] = useState(false);

  const handleExport = (format: "json" | "csv" | "markdown" | "pdf") => {
    const baseName = `atlas-${data.vertical}-${(data.city ?? "result").toLowerCase().replace(/\s+/g, "-")}-${Date.now()}`;
    const resultUrl = typeof window !== "undefined" && resultId
      ? `${window.location.origin}/result/${resultId}`
      : undefined;
    const dataWithUrl = { ...data, resultUrl };
    if (format === "json") {
      downloadFile(`${baseName}.json`, JSON.stringify(dataWithUrl, null, 2), "application/json");
    } else if (format === "csv") {
      downloadFile(`${baseName}.csv`, toCSV(data.rankedSites), "text/csv");
    } else if (format === "markdown") {
      downloadFile(`${baseName}.md`, toMarkdown(dataWithUrl), "text/markdown");
    } else if (format === "pdf") {
      // Build a clean print-ready HTML doc — NO sidebar, NO buttons, NO chrome
      const mdHtml = toMarkdown(dataWithUrl)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/^# (.+)$/gm, "<h1>$1</h1>")
        .replace(/^## (.+)$/gm, "<h2>$1</h2>")
        .replace(/^### (.+)$/gm, "<h3>$1</h3>")
        .replace(/^\*\*([^*]+)\*\*:/gm, "<strong>$1:</strong>")
        .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
        .replace(/^- /gm, "• ")
        .replace(/\n/g, "<br>");

      const w = window.open("", "_blank");
      if (w) {
        w.document.write(`<!DOCTYPE html><html><head><title>Atlas — ${data.vertical}</title><style>
          body { font-family: -apple-system, system-ui, sans-serif; max-width: 720px; margin: 32px auto; padding: 0 24px; color: #18181b; line-height: 1.5; }
          h1 { color: #4F46E5; font-size: 22px; margin-bottom: 8px; }
          h2 { color: #4F46E5; font-size: 18px; border-bottom: 1px solid #e4e4e7; padding-bottom: 4px; margin-top: 28px; }
          h3 { font-size: 14px; margin-top: 20px; margin-bottom: 4px; }
          .meta { color: #71717a; font-size: 12px; margin-bottom: 4px; }
          .score { color: #4F46E5; font-weight: 600; }
          .competitors { font-size: 11px; color: #71717a; }
          hr { border: none; border-top: 1px solid #e4e4e7; margin: 24px 0; }
          a { color: #4F46E5; }
          @media print { body { margin: 0; padding: 16px; } }
        </style></head><body>${mdHtml}</body></html>`);
        w.document.close();
        setTimeout(() => w.print(), 500);
      }
      return;
    }
    setOpen(false);
  };

  return (
    <div className="relative">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="inline-flex items-center gap-1.5 rounded-md border border-atlas-border bg-atlas-surface px-3 py-1.5 text-xs text-atlas-text transition-colors hover:border-atlas-accent"
        aria-label="Export result"
      >
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
          <polyline points="7 10 12 15 17 10" />
          <line x1="12" y1="15" x2="12" y2="3" />
        </svg>
        Export
      </button>
      {open && (
        <div className="absolute right-0 mt-1 w-44 rounded-md border border-atlas-border bg-atlas-surface p-1 shadow-lg shadow-black/30 z-50">
          {[
            { k: "markdown" as const, l: "Markdown (.md)" },
            { k: "pdf" as const, l: "PDF (print)" },
            { k: "csv" as const, l: "CSV (spreadsheet)" },
            { k: "json" as const, l: "JSON (raw)" },
          ].map((opt) => (
            <button
              key={opt.k}
              type="button"
              onClick={() => handleExport(opt.k)}
              className="block w-full rounded px-3 py-1.5 text-left text-xs text-atlas-text hover:bg-atlas-surface2"
            >
              {opt.l}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
