"use client";

import { useState } from "react";

interface ExportData {
  question: string;
  vertical: string;
  city?: string;
  country?: string;
  model?: string;
  echo?: string;
  rankedSites: any[];
  plan?: any;
  answer?: string;
  sources?: any[];
}

function downloadFile(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function toCSV(sites: any[]): string {
  const header = "rank,name,suburb,score,confidence,lat,lng,rationale";
  const rows = sites.map((s) =>
    [
      s.rank,
      JSON.stringify(s.name ?? ""),
      JSON.stringify(s.suburb ?? ""),
      s.score ?? 0,
      s.confidence ?? 0,
      s.lat ?? 0,
      s.lng ?? 0,
      JSON.stringify((s.rationale ?? "").replace(/"/g, '""')),
    ].join(",")
  );
  return [header, ...rows].join("\n");
}

function toMarkdown(d: ExportData): string {
  const lines: string[] = [];
  lines.push(`# Atlas — ${d.vertical.replace(/_/g, " ")}`);
  lines.push("");
  lines.push(`**Question:** ${d.question}`);
  if (d.city) lines.push(`**City:** ${d.city}${d.country ? `, ${d.country}` : ""}`);
  lines.push(`**Model:** ${d.model ?? "Atlas Stub"}`);
  if (d.echo) lines.push(`**Status:** ${d.echo}`);
  lines.push("");
  if (d.answer) {
    lines.push("## Research Answer");
    lines.push(d.answer);
    lines.push("");
  }
  lines.push(`## Top ${d.rankedSites.length} Sites`);
  lines.push("");
  for (const s of d.rankedSites) {
    lines.push(`### ${s.rank}. ${s.name}${s.suburb ? ` — ${s.suburb}` : ""}`);
    lines.push(`**Score:** ${(s.score * 100).toFixed(0)}% · **Confidence:** ${(s.confidence * 100).toFixed(0)}%`);
    lines.push(`**Location:** ${s.lat?.toFixed(4)}, ${s.lng?.toFixed(4)}`);
    if (s.rationale) lines.push(`**Why:** ${s.rationale}`);
    if (s.advantages) {
      lines.push("**Advantages:**");
      const advs = s.advantages;
      if (advs.economic) lines.push(`- Economic: ${advs.economic}`);
      if (advs.geographic) lines.push(`- Geographic: ${advs.geographic}`);
      if (advs.logistical) lines.push(`- Logistical: ${advs.logistical}`);
      if (advs.demographic) lines.push(`- Demographic: ${advs.demographic}`);
    }
    if (s.disadvantages) lines.push(`**Drawbacks:** ${s.disadvantages}`);
    if (s.competition && Array.isArray(s.competition) && s.competition.length > 0) {
      lines.push(`**Nearby competitors:** ${s.competition.slice(0, 5).join(", ")}`);
    }
    lines.push("");
  }
  if (d.sources && d.sources.length > 0) {
    lines.push("## Sources");
    for (const s of d.sources) {
      lines.push(`- [${s.title ?? s.url}](${s.url})`);
    }
    lines.push("");
  }
  lines.push("---");
  lines.push(`Generated by Atlas · ${new Date().toISOString()}`);
  return lines.join("\n");
}

export function ResultExportButton({ data }: { data: ExportData }) {
  const [open, setOpen] = useState(false);

  const handleExport = (format: "json" | "csv" | "markdown" | "pdf") => {
    const baseName = `atlas-${data.vertical}-${(data.city ?? "result").toLowerCase().replace(/\s+/g, "-")}-${Date.now()}`;
    if (format === "json") {
      downloadFile(`${baseName}.json`, JSON.stringify(data, null, 2), "application/json");
    } else if (format === "csv") {
      downloadFile(`${baseName}.csv`, toCSV(data.rankedSites), "text/csv");
    } else if (format === "markdown") {
      downloadFile(`${baseName}.md`, toMarkdown(data), "text/markdown");
    } else if (format === "pdf") {
      // Use browser print-to-PDF for instant PDF
      const w = window.open("", "_blank");
      if (w) {
        w.document.write(`<!DOCTYPE html><html><head><title>Atlas — ${data.vertical}</title><style>body{font-family:-apple-system,system-ui,sans-serif;max-width:720px;margin:32px auto;padding:0 24px;color:#18181b;line-height:1.5}h1{color:#4F46E5}table{border-collapse:collapse;width:100%;margin:16px 0}th,td{text-align:left;padding:8px;border-bottom:1px solid #e4e4e7}th{background:#f4f4f5;font-size:11px;text-transform:uppercase}.meta{color:#71717a;font-size:12px}@media print{body{margin:0}}</style></head><body>${document.body.innerHTML}</body></html>`);
        w.document.close();
        setTimeout(() => w.print(), 500);
      }
      return;
    }
    setOpen(false);
  };

  return (
    <div className="relative">
      <button
        type="button"
        onClick={() => setOpen((o) => !o)}
        className="inline-flex items-center gap-1.5 rounded-md border border-atlas-border bg-atlas-surface px-3 py-1.5 text-xs text-atlas-text transition-colors hover:border-atlas-accent"
        aria-label="Export result"
      >
        <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
          <polyline points="7 10 12 15 17 10" />
          <line x1="12" y1="15" x2="12" y2="3" />
        </svg>
        Export
      </button>
      {open && (
        <div className="absolute right-0 mt-1 w-44 rounded-md border border-atlas-border bg-atlas-surface p-1 shadow-lg shadow-black/30 z-50">
          {[
            { k: "markdown" as const, l: "Markdown (.md)" },
            { k: "pdf" as const, l: "PDF (print)" },
            { k: "csv" as const, l: "CSV (spreadsheet)" },
            { k: "json" as const, l: "JSON (raw)" },
          ].map((opt) => (
            <button
              key={opt.k}
              type="button"
              onClick={() => handleExport(opt.k)}
              className="block w-full rounded px-3 py-1.5 text-left text-xs text-atlas-text hover:bg-atlas-surface2"
            >
              {opt.l}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
