/**
 * Split lib/stub/real-sites.ts into per-city files to reduce build
 * complexity and rule out size-related issues on Vercel.
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";

const SRC = join(__dirname, "../lib/stub/real-sites.ts");
const OUT_DIR = join(__dirname, "../lib/stub/catalog");

mkdirSync(OUT_DIR, { recursive: true });

const content = readFileSync(SRC, "utf-8");

// Find the REAL_SITE_CATALOG object boundaries
const start = content.indexOf("export const REAL_SITE_CATALOG");
const end = content.indexOf("\n};\n", start) + 3;
const block = content.slice(start, end);

// Find each city block (top-level entries)
const cityRe = /^  ([a-z_]+): \{/gm;
const cities: Array<{ id: string; start: number; end: number }> = [];
let match;
while ((match = cityRe.exec(block)) !== null) {
  cities.push({ id: match[1], start: match.index });
}
for (let i = 0; i < cities.length; i++) {
  const endIdx = i + 1 < cities.length ? cities[i + 1].start : block.length;
  cities[i].end = endIdx;
}

// Write per-city file
for (const city of cities) {
  const cityBlock = block.slice(city.start, city.end);
  const out = `/**
 * AUTO-GENERATED by scripts/split-catalog.ts — ${city.id} entries.
 * Source: lib/stub/real-sites.ts (before split).
 */
import type { RealSite } from "../real-sites-types";

export const ${city.id.toUpperCase()}_SITES: Record<string, RealSite[]> = ${cityBlock.trimEnd().replace(/^  [a-z_]+: \{/, "{\n  ").replace(/^  ([a-z_]+): \[/gm, "  $1:")};
`;
  const outPath = join(OUT_DIR, `${city.id}.ts`);
  writeFileSync(outPath, out, "utf-8");
  console.log(`Written ${outPath}`);
}

console.log(`\nTotal cities: ${cities.length}`);
